---
title: "Practical_0"
output: html_document
author: Berke Sahin
date: "2025-05-15"
---

# Practical 0
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Load Required Packages
```{r load-packages}
library(tidyverse)
library(datasauRus)
```

```{r}
?datasaurus_dozen
```

Datasaurus is a data frame with 1846 rows and 3 variables (dataset, x, and y).

## Data
```{r data-preview}
datasaurus_dozen %>% 
  count(dataset)
```
## Data Visualization and Summary

### Dino Dataset

```{r dino-filter}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
```

```{r dino-plot}
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r dino-cor}
dino_data %>%
  summarize(r = cor(x, y))
```

### Star Dataset

```{r star-filter}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")
```

```{r star-plot}
ggplot(data = star_data, aes(x = x, y = y)) +
  geom_point()
```

```{r star-cor}
star_data %>%
  summarize(r = cor(x, y))
```
r for dino was -0.06447185, whereas it's -0.0629611	for star. 
### Circle Dataset

```{r circle-filter}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")
```

```{r circle-plot}
ggplot(data = circle_data, aes(x = x, y = y)) +
  geom_point()
```

```{r circle-cor}
circle_data %>%
  summarize(r = cor(x, y))
```
r for circle is -0.06834336 compared to the previously calculated r of -0.06447185 for dino. 

## All Datasets Faceted

```{r facet-plot, fig.width=10, fig.height=8}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset)) +
  geom_point() +
  facet_wrap(~ dataset, ncol = 3) +
  theme(legend.position = "none")
```

## Correlation by Dataset

```{r all-correlations}
datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y))
```
